In [1]:
import pandas as pd

In [53]:
crashes = pd.read_csv('crashes.csv')
#fill na values with 0 on injuires fatal and incapacitating
crashes['INJURIES_FATAL'] = crashes['INJURIES_FATAL'].fillna(0)
crashes['INJURIES_INCAPACITATING'] = crashes['INJURIES_INCAPACITATING'].fillna(0)
crashes["SRINJURIES"]= crashes["INJURIES_FATAL"] + crashes["INJURIES_INCAPACITATING"]

In [74]:
#sum of serious injuries between 2019-01-06 and 2019-01-12
crashes[(crashes['CRASH_DATE'] >= '2023-12-24') & (crashes['CRASH_DATE'] <= '2023-12-30')]["SRINJURIES"].sum()

28.0

In [38]:
crashes = pd.read_csv('crashes.csv')
#fill na values with 0 on injuires fatal and incapacitating
crashes['INJURIES_FATAL'] = crashes['INJURIES_FATAL'].fillna(0)
crashes['INJURIES_INCAPACITATING'] = crashes['INJURIES_INCAPACITATING'].fillna(0)
crashes["SRINJURIES"]= crashes["INJURIES_FATAL"] + crashes["INJURIES_INCAPACITATING"]
#apply date format to CRASH_DATE
crashes['CRASH_DATE'] = pd.to_datetime(crashes['CRASH_DATE'])

In [39]:
# Ensure 'CRASH_DATE' is the index for resampling
crashes.set_index('CRASH_DATE', inplace=True)

# Aggregate by the default weekly period (starting on Sunday), counting crashes and summing 'SRINJURIES'
weekly_crashes = crashes.resample('W').agg(
    Weekly_Crash_Count=('SRINJURIES', 'size'),     # Count of crashes
    Weekly_Severe_Injuries=('SRINJURIES', 'sum')   # Sum of severe injuries
)

# Reset the index if you want the date as a column
weekly_crashes = weekly_crashes.reset_index()

print(weekly_crashes)

    CRASH_DATE  Weekly_Crash_Count  Weekly_Severe_Injuries
0   2019-01-06                1545                    38.0
1   2019-01-13                2108                    39.0
2   2019-01-20                1944                    27.0
3   2019-01-27                2256                    36.0
4   2019-02-03                2185                    28.0
..         ...                 ...                     ...
256 2023-12-03                2270                    37.0
257 2023-12-10                2122                    30.0
258 2023-12-17                2191                    40.0
259 2023-12-24                2138                    48.0
260 2023-12-31                1614                    26.0

[261 rows x 3 columns]

In [40]:
max(crashes['CRASH_DATE'])

KeyError: 'CRASH_DATE'

In [36]:
# Ensure 'CRASH_DATE' is the index for resampling
crashes.set_index('CRASH_DATE', inplace=True)

# Aggregate by week and count the number of crashes per week
weekly_crashes = crashes.resample('W').size()

# Rename the result column for clarity
weekly_crashes = weekly_crashes.rename('Weekly_Crash_Count')

# Convert back to a DataFrame if needed
weekly_crashes_df = weekly_crashes.reset_index()

print(weekly_crashes_df)

    CRASH_DATE  Weekly_Crash_Count
0   2019-01-06                1545
1   2019-01-13                2108
2   2019-01-20                1944
3   2019-01-27                2256
4   2019-02-03                2185
..         ...                 ...
256 2023-12-03                2270
257 2023-12-10                2122
258 2023-12-17                2191
259 2023-12-24                2138
260 2023-12-31                1614

[261 rows x 2 columns]

In [33]:
min(crashes['CRASH_DATE'])

Timestamp('2019-01-01 00:00:00')

In [34]:
max(crashes['CRASH_DATE'])

Timestamp('2023-12-31 00:00:00')

In [27]:
# Group by week and sum the number of crashes and serious injuries
weekly_summary = crashes.groupby('WEEK').agg({
    'CRASH_DATE': 'count',   # Count of crashes per week
    'SRINJURIES': 'sum'      # Sum of serious injuries per week
}).rename(columns={'CRASH_DATE': 'NUM_CRASHES', 'SRINJURIES': 'TOTAL_SERIOUS_INJURIES'}).reset_index()

In [28]:
weekly_summary

   WEEK  NUM_CRASHES  TOTAL_SERIOUS_INJURIES
0    00         3169                    86.0
1    01         8740                   199.0
2    02         9238                   172.0
3    03         9552                   204.0
4    04         9866                   154.0
5    05        10265                   193.0
6    06        10718                   191.0
7    07        10585                   169.0
8    08        10225                   201.0
9    09         9733                   214.0
10   10         9725                   213.0
11   11         9524                   197.0
12   12         8753                   211.0
13   13         9080                   169.0
14   14         8943                   223.0
15   15         8990                   202.0
16   16         9170                   190.0
17   17        10080                   204.0
18   18        10514                   220.0
19   19        10586                   276.0
20   20        10502                   220.0
21   21        10710                   251.0
22   22        11086                   306.0
23   23        11253                   287.0
24   24        11221                   281.0
25   25        11255                   306.0
26   26        10956                   274.0
27   27        10862                   291.0
28   28        10888                   261.0
29   29        10873                   285.0
30   30        11223                   311.0
31   31        10978                   274.0
32   32        10681                   229.0
33   33        10490                   250.0
34   34        10937                   282.0
35   35        11267                   288.0
36   36        10643                   274.0
37   37        11416                   279.0
38   38        11063                   244.0
39   39        10964                   264.0
40   40        11030                   250.0
41   41        10449                   257.0
42   42        10680                   230.0
43   43        11461                   262.0
44   44        10635                   226.0
45   45        10386                   195.0
46   46        10461                   200.0
47   47         9103                   244.0
48   48         9699                   207.0
49   49        10410                   208.0
50   50        10274                   239.0
51   51         9379                   226.0
52   52         6796                   132.0
53   53          273                     2.0

In [4]:
#fill na values with 0 on injuires fatal and incapacitating
crashes['INJURIES_FATAL'] = crashes['INJURIES_FATAL'].fillna(0)
crashes['INJURIES_INCAPACITATING'] = crashes['INJURIES_INCAPACITATING'].fillna(0)

In [6]:
crashes["SRINJURIES"]= crashes["INJURIES_FATAL"] + crashes["INJURIES_INCAPACITATING"]

In [8]:
#apply date format to CRASH_DATE
crashes['CRASH_DATE'] = pd.to_datetime(crashes['CRASH_DATE'])

In [10]:
#craate a variable of week starking sunday as first date
crashes['WEEK_DAY'] = crashes['CRASH_DATE'].dt.day_name()

In [13]:
#sort by crsh date
crashes = crashes.sort_values(by='CRASH_DATE')

In [25]:
# Create a new column 'week' where the week starts on Sunday as the first day of the week
crashes['WEEK'] = crashes['CRASH_DATE'].dt.strftime('%U')

In [26]:
crashes['WEEK'].head(50)

407444    00
487534    00
366924    00
228350    00
454544    00
13600     00
240822    00
397106    00
211295    00
147548    00
323382    00
260134    00
223017    00
147675    00
293595    00
436760    00
461731    00
415881    00
345262    00
345255    00
436591    00
494121    00
369446    00
514756    00
66123     00
7543      00
205115    00
94575     00
444832    00
364337    00
262988    00
518578    00
279875    00
74281     00
366749    00
262428    00
518772    00
131448    00
95388     00
478433    00
112035    00
46121     00
22464     00
74583     00
528558    00
423106    00
501500    00
369655    00
369794    00
318808    00
Name: WEEK, dtype: object